/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  /**
   * Reference to this schema.
   */
  $schema: "config.schema.json";
  /**
   * The bot's Discord token.
   */
  token: string;
  /**
   * The bot's Discord client ID.
   */
  clientId: string;
  /**
   * The ID of the Discord guild the bot is installed to.
   */
  guildId: string;
  /**
   * The ID of the role with moderator privileges.
   */
  moderatorRoleId: string;
  /**
   * The ID of the channel to send moderation logs to.
   */
  moderationLogChannelId: string;
  /**
   * The ID of the channel to send leveling up messages in.
   */
  levelingChannelId: string;
  /**
   * The ID of the channel for the counting activity.
   */
  countingChannelId: string;
}
