/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ConfigSchema {
  /**
   * Reference to this schema.
   */
  $schema: "config.schema.json";
  /**
   * API key for the Suroi API.
   */
  suroiApiKey: string;
  /**
   * The bot's Discord token.
   */
  token: string;
  /**
   * Path to the yt-dlp executable used to download YouTube videos for the /song command.
   */
  youtubeDownloaderPath: string;
  /**
   * The bot's Discord client ID.
   */
  clientId: string;
  /**
   * The ID of the main Discord guild the bot is installed to.
   */
  mainGuildId: string;
  /**
   * The ID of the game modding Discord guild the bot is installed to.
   */
  policeGuildId: string;
  /**
   * The ID of the channel to send moderation logs to.
   */
  moderationLogChannelId: string;
  /**
   * The ID of the channel to send leveling up messages in.
   */
  levelingChannelId: string;
  /**
   * The ID of the channel to use for the starboard.
   */
  starboardChannelId: string;
  /**
   * The ID of the emoji to use for the starboard.
   */
  starboardEmojiId: string;
  /**
   * The name of the emoji to use for the starboard.
   */
  starboardEmojiName: string;
  /**
   * The ID of the channel for the counting activity.
   */
  countingChannelId: string;
  /**
   * The ID of the channel in the police server to send punishment logs to.
   */
  gameModLogChannelId: string;
  /**
   * Roles that are allowed to perform game mod actions.
   */
  gameModRoles: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` ".*".
     */
    [k: string]: ("warn" | "temp" | "perma" | "whitelist" | "unban")[];
  };
}
